### ISSUE TITLE
Error when importing TensorFlow and DeepSpeech in the same Python interpreter

### ISSUE THREAD

**Issue by DaniFojo** [mozilla/DeepSpeech#1288]
I get an error when importing TensorFlow and DeepSpeech in the same Python interpreter. I am not using GPU.

- **Have I written custom code (as opposed to running examples on an unmodified clone of the repository)**: I have not.
- **OS Platform and Distribution**: I have tested both in OSX and Ubuntu, and both give the same error.
- **TensorFlow installed from**: PyPI
- **TensorFlow version**: I got the same error in 1.2, 1.4 and 1.5
- **Python version**: 2.7                

- **Exact command to reproduce**: 
```python
from deepspeech.model import Model
import tensorflow
```
 gives the traceback:
```
F tensorflow/stream_executor/host/host_platform.cc:112] Non-OK-status: gpu::MultiPlatformManager::RegisterPlatform(std::move(platform)) status: Internal: platform is already registered with name: "Host"
Aborted (core dumped)
```
even though I'm not using GPU.

In the other order:
```python
from deepspeech.model import Model
import tensorflow
```
 I get the traceback (too long to paste here): https://gist.github.com/DaniFojo/dc6f52132394420da32bc07ec9a80db1

**Comment by lissyx** [comment]
@DaniFojo Can you please document your steps for setup ?

**Comment by DaniFojo** [comment]
Just doing `from deepspeech.model import Model` followed by `import tensorflow` in a command line Python interpreter gives the error. Thanks!

**Comment by lissyx** [comment]
@DaniFojo And I just said that we explicitely test this, so we know it works. So I need to know how you setup things to be able to investigate what is wrong.

**Comment by DaniFojo** [comment]
I have tried it in many configurations and it hasn't work in any of them. In a new clean virtualenviroment in Ubuntu 16.04, doing `pip install tensorflow==1.2` and `pip install deepspeech` (without gpu support) followed by importing both gives the error. [These](https://gist.github.com/DaniFojo/5bae13387d14cae7e22d564ad1867cfd) are the steps I do to get the error.

**Comment by lissyx** [comment]
@DaniFojo Try to use `tensorflow==1.5.0` and DeepSpeech from TaskCluster: https://tools.taskcluster.net/index/project.deepspeech.deepspeech.native_client.master/cpu so: `pip install --upgrade https://index.taskcluster.net/v1/task/project.deepspeech.deepspeech.native_client.master.cpu/artifacts/public/deepspeech-0.1.1-cp27-cp27mu-manylinux1_x86_64.whl`

It works for me.

**Comment by DaniFojo** [comment]
I just tried it with tensorflow 1.2 and DeepSpeech from TaskCluster and it works, thanks! How is it that the version from PyPI doesn't work?

**Comment by lissyx** [comment]
Likely because the one from PyPi is « old » and does not include #1127, which allowed us to hide symbols from TensorFlow, thus avoiding that kind of collisions.
