### ISSUE TITLE
ImportError: libcublas.so.10.0: cannot open shared object file: No such file or directory

### ISSUE THREAD

**Issue by superdutyf3** [mozilla/DeepSpeech#2285]
Hello,
I'm using pip3 install deepspeech-gpu (also tried downloading files from github)
Linux Ubuntu 18.04
upstream TensorFlow
v1.14.0-rc1-22-gaf24dc91b5 1.14.0
python 3.6**: 
gcc (Ubuntu 7.4.0-1ubuntu1~18.04.1) 7.4.0
cuda 10
cudnn 7.5
GT1050 2GB
try to run deepspeech, get this error

(deepspeech-venv) shop@shop-T3610:~$ deepspeech
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/dist-packages/deepspeech/impl.py", line 14, in swig_import_helper
    return importlib.import_module(mname)
  File "/usr/lib/python3.6/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 994, in _gcd_import
  File "<frozen importlib._bootstrap>", line 971, in _find_and_load
  File "<frozen importlib._bootstrap>", line 955, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 658, in _load_unlocked
  File "<frozen importlib._bootstrap>", line 571, in module_from_spec
  File "<frozen importlib._bootstrap_external>", line 922, in create_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
ImportError: libcublas.so.10.0: cannot open shared object file: No such file or directory

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/bin/deepspeech", line 7, in <module>
    from deepspeech.client import main
  File "/usr/local/lib/python3.6/dist-packages/deepspeech/__init__.py", line 14, in <module>
    from deepspeech.impl import PrintVersions as printVersions
  File "/usr/local/lib/python3.6/dist-packages/deepspeech/impl.py", line 17, in <module>
    _impl = swig_import_helper()
  File "/usr/local/lib/python3.6/dist-packages/deepspeech/impl.py", line 16, in swig_import_helper
    return importlib.import_module('_impl')
  File "/usr/lib/python3.6/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
ModuleNotFoundError: No module named '_impl'

Please help! Been working on this for days...

**Comment by lissyx** [comment]
>  ImportError: libcublas.so.10.0: cannot open shared object file: No such file or directory

Obviously, you don't have proper CUDA 10.0 installed.

**Comment by pratapaprasanna** [comment]
If you already have cuda installed then try setting your environment variable `LD_LIBRARY_PATH`
eg:
In my case
`export LD_LIBRARY_PATH=/usr/local/cuda-10.0/lib64`
worked for me .

**Comment by superdutyf3** [comment]
pratapaprasanna 
Thank you very much. That worked. Cuda is installed and everything is working!!!!

**Comment by lissyx** [comment]
> pratapaprasanna
> Thank you very much. That worked. Cuda is installed and everything is working!!!!

Thanks for updating us, I'm closing this :)
