### ISSUE TITLE
My cuda version was 10.1，it is necessary this code run in cuda10.0？

### ISSUE THREAD

**Issue by HandsLing** [mozilla/DeepSpeech#2861]
hope for your reply

**Comment by reuben** [comment]
The official TensorFlow documentation seems to indicate that 10.1 is fine, but the docs have not been very well kept during the 1.x -> 2.x transition period, so you'll have to test for yourself. We've been using 10.0 for a long time now.

**Comment by reuben** [comment]
https://www.tensorflow.org/install/gpu

**Comment by HandsLing** [comment]
@reuben when i use deepspeech with trained model, it turns out the error:ImportError: libcublas.so.10.0: cannot open shared object file: No such file or directory
and i install deepspeech with : pip3 install deepspeech-gpu
so can i change somewhere to make deepspeech surpport cuda10.1
